const words = {
        en: { statement:'The bank<br>for a changing world', language:'Choose your language', welcome:'Welcome to', privateBank:'Your online private bank', wealthCopy:'Manage your wealth<br>simply and securely.', benefitOne:'A complete view<br>of your assets', benefitTwo:'Secure and<br>reliable access', benefitThree:'A dedicated team<br>by your side', accessTitle:'Access your accounts', accessSubtitle:'Enter your client identifier to continue.', clientLabel:'Client / User ID', continue:'Continue', or:'or', qrTitle:'Log in with QR code', qrSubtitle:'Use the BNP Paribas myWealth app', helpTitle:'Need help logging in?', forgot:"I've forgotten my identifier", assistance:'I need assistance', securityTitle:'Your security is our priority', securityCopy:'myWealth uses multi-factor authentication to protect your data and transactions.', securityLink:'Learn more about security', sustainable:'BUILDING A SUSTAINABLE TOMORROW', rights:'All rights reserved.', placeholder:'Enter your identifier' },
        fr: { statement:'La banque<br>pour un monde qui change', language:'Choisissez votre langue', welcome:'Bienvenue dans', privateBank:'Votre banque privée en ligne', wealthCopy:'Gérez votre patrimoine<br>simplement et en toute sécurité.', benefitOne:'Une vision complète<br>de vos avoirs', benefitTwo:'Un accès sûr<br>et fiable', benefitThree:'Une équipe dédiée<br>à vos côtés', accessTitle:'Accédez à vos comptes', accessSubtitle:'Saisissez votre identifiant client pour continuer.', clientLabel:'Identifiant client / utilisateur', continue:'Continuer', or:'ou', qrTitle:'Connexion par QR code', qrSubtitle:"Utilisez l’application BNP Paribas myWealth", helpTitle:'Besoin d’aide pour vous connecter ?', forgot:"J’ai oublié mon identifiant", assistance:"J’ai besoin d’assistance", securityTitle:'Votre sécurité est notre priorité', securityCopy:'myWealth utilise une authentification à plusieurs facteurs pour protéger vos données.', securityLink:'En savoir plus sur la sécurité', sustainable:'CONSTRUIRE UN AVENIR DURABLE', rights:'Tous droits réservés.', placeholder:'Saisissez votre identifiant' },
        de: { statement:'Die Bank<br>für eine Welt im Wandel', language:'Wählen Sie Ihre Sprache', welcome:'Willkommen bei', privateBank:'Ihre Online-Privatbank', wealthCopy:'Verwalten Sie Ihr Vermögen<br>einfach und sicher.', benefitOne:'Ein vollständiger Überblick<br>über Ihre Vermögenswerte', benefitTwo:'Sicherer und<br>zuverlässiger Zugang', benefitThree:'Ein persönliches Team<br>an Ihrer Seite', accessTitle:'Zugang zu Ihren Konten', accessSubtitle:'Geben Sie Ihre Kundenkennung ein, um fortzufahren.', clientLabel:'Kunden- / Benutzerkennung', continue:'Weiter', or:'oder', qrTitle:'Mit QR-Code anmelden', qrSubtitle:'Nutzen Sie die BNP Paribas myWealth App', helpTitle:'Brauchen Sie Hilfe bei der Anmeldung?', forgot:'Ich habe meine Kennung vergessen', assistance:'Ich benötige Unterstützung', securityTitle:'Ihre Sicherheit hat Priorität', securityCopy:'myWealth verwendet eine Mehrfaktor-Authentifizierung zum Schutz Ihrer Daten.', securityLink:'Mehr über Sicherheit erfahren', sustainable:'EINE NACHHALTIGE ZUKUNFT GESTALTEN', rights:'Alle Rechte vorbehalten.', placeholder:'Geben Sie Ihre Kennung ein' }
      };
      const identifier = document.getElementById('client-id');
      const setLoginMessage = (text, tone = '') => {
        const message = document.getElementById('login-message');
        message.textContent = text;
        message.classList.toggle('is-progress', tone === 'progress');
        message.classList.toggle('is-error', tone === 'error');
      };
      document.querySelectorAll('[data-locale]').forEach(tab => tab.addEventListener('click', () => { const locale = tab.dataset.locale, set = words[locale]; document.documentElement.lang = locale; document.querySelectorAll('[data-t]').forEach(el => el.innerHTML = set[el.dataset.t]); identifier.placeholder = set.placeholder; document.querySelectorAll('[data-locale]').forEach(item => { const selected = item === tab; item.classList.toggle('active', selected); item.setAttribute('aria-selected', selected); }); }));
      setLoginMessage('Please verify your client credentials to initiate secure authentication.');
      document.getElementById('login-form').addEventListener('submit', event => {
        event.preventDefault();
        setLoginMessage('Starting the Luxtrust authentication sequence…', 'progress');
        window.location.assign('./authentication.html');
      });
      const modal = document.getElementById('info-modal'), modalTitle = document.getElementById('modal-title'), modalCopy = document.getElementById('modal-copy'), modalQr = modal.querySelector('.dialog-qr');
      const modals = { qr:['Open myWealth on your device','Use the myWealth app to scan this code and continue securely on your registered device.',true], identifier:['Find your identifier','Your client identifier is included in your myWealth welcome information. For help locating it, contact your relationship manager.'], assistance:['We are here to help','Client support is available Monday to Friday, from 08:00 to 18:00 CET. Your relationship manager can also assist with access to myWealth.'], security:['Security for your myWealth access','Always verify the website address before signing in. myWealth never asks you to share a security code by phone or email.'], legal:['Legal information','This interactive page is an illustrative myWealth experience. For account-specific information, contact your relationship manager.'], cookies:['Cookies','This local demonstration stores no login identifier and does not use optional cookies for sign-in.'] };
      document.querySelectorAll('[data-modal]').forEach(button => button.addEventListener('click', () => { const item = modals[button.dataset.modal]; modalTitle.textContent = item[0]; modalCopy.textContent = item[1]; modalQr.hidden = !item[2]; modal.showModal(); }));
      modal.querySelectorAll('.dialog-close,.dialog-action').forEach(button => button.addEventListener('click', () => modal.close())); modal.addEventListener('click', event => { if (event.target === modal) modal.close(); });
      document.getElementById('help-toggle').addEventListener('click', event => { const open = event.currentTarget.getAttribute('aria-expanded') === 'true'; event.currentTarget.setAttribute('aria-expanded', !open); document.getElementById('help-links').hidden = open; });
