import {useState} from 'react'; import {navigation} from './data/navigation'; import './styles/site.css';

const designPath='/lu/en/your-goals/protect-and-grow-your-wealth/design-your-portfolio.html';

function Header(){const[open,setOpen]=useState(false);return <><div className="utility"><button>LUXEMBOURG⌄</button><span>EN　 FR</span></div><header><a className="brand" href="/"><b>BNP</b><strong>PARIBAS</strong><small>WEALTH MANAGEMENT</small></a><button className="hamb" onClick={()=>setOpen(!open)} aria-expanded={open}>☰</button><nav className={open?'nav open':'nav'}>{navigation.map(n=><div className="navitem" key={n.label}><a href={n.href}>{n.label}</a>{n.children&&<div className="drop">{n.children.map(c=><a href={c.href} key={c.label}>{c.label}</a>)}</div>}</div>)}</nav><button className="search">⌕</button></header></>}

function Footer(){return <footer><div className="footgrid"><div><div className="footbrand">BNP PARIBAS<br/><span>WEALTH MANAGEMENT</span></div><p>Private banking and wealth management expertise in Luxembourg.</p></div><div><h4>WEALTH MANAGEMENT</h4><a href={designPath}>Design your portfolio</a><a href="#">Investment universe</a><a href="#">Level of service</a></div><div><h4>USEFUL LINKS</h4><a href="#">Contact us</a><a href="#">Privacy</a><a href="#">Legal information</a></div></div><div className="footbottom">© BNP Paribas Wealth Management <span>Accessibility · Cookies</span></div></footer>}

function DesignPortfolio(){return <><Header/><main className="portfolio"><section className="pagehero"><div><p className="eyebrow">YOUR GOALS · PROTECT &amp; GROW YOUR WEALTH</p><h1>Design your portfolio</h1><p>Build an investment strategy designed around your objectives, preferences and desired level of involvement.</p></div></section><section className="strategy"><div className="strategycopy"><p className="eyebrow">INVESTMENT STRATEGY</p><h2>Coherence &amp; clarity</h2><p>A team of in-house strategists will remain by your side to translate macro-economic and market events into actionable investment ideas.</p></div><div className="strategyvisual"><div className="dashboard"><span>STRATEGIC ASSET ALLOCATION</span><div className="bars"><i/><i/><i/><i/><i/></div><div className="dashline"/></div></div></section><section className="three"><article><div className="icon">◌</div><h3>Research &amp; Guidance</h3><p>Our team of strategists analyse and explain complex situations and concepts.</p></article><article><div className="icon">◫</div><h3>Responsiveness</h3><p>Our strategists react to market events in real time by producing top-quality research.</p></article><article><div className="icon">↗</div><h3>Actionable investment ideas</h3><p>The annual Investment Themes are updated on a quarterly basis.</p></article></section><section className="themes"><div><p className="eyebrow">INVESTMENT THEMES</p><h2>Turn market insight into investment ideas.</h2><p>Explore the latest investment themes and the research supporting our strategic approach.</p><a className="button" href="#">LEARN MORE ABOUT OUR 2026 INVESTMENT THEMES</a></div><div className="themeimage"><div className="themechart"><span>2026</span><b>INVESTMENT<br/>THEMES</b><em>STRATEGY · DIVERSIFICATION · LONG TERM</em></div></div></section><section className="more"><p className="eyebrow">MORE INFORMATION?</p><h2>Let's discuss your wealth and your investment objectives.</h2><div className="actions"><a href="#">BOOK AN APPOINTMENT →</a><a href="#">TELL US ABOUT YOUR PROJECT →</a><a href="#">REQUEST FOR PROPOSAL →</a></div></section></main><Footer/></>}

function Home(){return <><Header/><section className="homehero"><div><p className="eyebrow">BNP PARIBAS WEALTH MANAGEMENT</p><h1>Our 2026 Investment Themes</h1><p>Mid-Year Update</p><a className="button light" href={designPath}>Discover our updated investment themes for 2026</a></div></section><section className="homeintro"><p className="eyebrow">LUXEMBOURG</p><h2>Expertise for your wealth, your projects and your future.</h2><a href={designPath}>Explore wealth-management solutions →</a></section><Footer/></>}

export default function App(){const path=window.location.pathname; return path.includes('/your-goals/protect-and-grow-your-wealth/design-your-portfolio')?<DesignPortfolio/>:<Home/>}