import { useState } from 'react'
import { navigation } from './data/navigation'
import logoSymbol from './assets/bnp-paribas-symbol.jpg'
import './styles/site.css'
import './styles/brand.css'

const routes = {
  portfolio: '/lu/en/your-goals/protect-and-grow-your-wealth/design-your-portfolio.html',
  universe: '/lu/en/your-goals/protect-and-grow-your-wealth/investment-universe.html',
  service: '/lu/en/your-goals/protect-and-grow-your-wealth/level-of-service.html',
  future: '/lu/en/your-goals/prepare-for-your-future.html',
  finance: '/lu/en/your-goals/finance-your-projects.html',
  about: '/lu/en/about-you.html',
  insights: '/lu/en/insights.html',
}

type HeroProps = { eyebrow: string; title: string; copy: string; tone?: 'moss' | 'ink' }

function Header() {
  const [menuOpen, setMenuOpen] = useState(false)
  return <><div className="utility-bar"><div className="utility-inner"><button type="button">LUXEMBOURG <span>⌄</span></button><div><button className="is-active" type="button">EN</button><button type="button">FR</button></div></div></div><header className="site-header"><a className="brand" href="/" aria-label="BNP Paribas Wealth Management home"><span className="brand-monogram" aria-hidden="true"><img src={logoSymbol} alt=""/></span><span><strong>BNP PARIBAS</strong><small>WEALTH MANAGEMENT</small></span></a><button className="menu-toggle" type="button" aria-expanded={menuOpen} aria-controls="primary-navigation" onClick={() => setMenuOpen(!menuOpen)}><span className="sr-only">Toggle navigation</span><span/><span/></button><nav id="primary-navigation" className={menuOpen ? 'main-nav is-open' : 'main-nav'} aria-label="Primary navigation">{navigation.map((item) => <div className="nav-group" key={item.label}><a href={item.href}>{item.label}</a>{item.children && <div className="subnav">{item.children.map((child) => <a href={child.href} key={child.label}>{child.label}</a>)}</div>}</div>)}</nav><a className="header-cta" href="#contact">Start a conversation <b>↗</b></a></header></>
}

function Footer() { return <footer className="site-footer"><div className="footer-grid"><div><a className="footer-brand" href="/"><span>BNP</span> BNP PARIBAS<br/>WEALTH MANAGEMENT</a><p>Private banking and wealth management expertise in Luxembourg.</p></div><div><h2>WEALTH MANAGEMENT</h2><a href={routes.portfolio}>Design your portfolio</a><a href={routes.universe}>Investment universe</a><a href={routes.service}>Level of service</a></div><div><h2>USEFUL LINKS</h2><a href="#contact">Contact us</a><a href="#">Privacy</a><a href="#">Legal information</a></div></div><div className="footer-bottom"><span>© BNP Paribas Wealth Management</span><span>Accessibility · Cookies</span></div></footer> }

function PageHero({ eyebrow, title, copy, tone = 'moss' }: HeroProps) { return <section className={`page-hero page-hero--${tone}`}><div className="hero-orbit" aria-hidden="true"><i/><i/><i/></div><div className="page-hero__inner"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{copy}</p><span className="hero-scroll">SCROLL TO EXPLORE <b>↓</b></span></div></section> }
function PageIntro({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <section className="page-intro"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><p>{copy}</p></section> }
function ContactBand() { return <section className="contact-band" id="contact"><p className="eyebrow">LET'S TALK</p><h2>Tell us about your project.</h2><p>Begin with a conversation. We’ll bring the right people to the table.</p><a className="button button--light" href="#">Contact us <b>↗</b></a></section> }

function DesignPortfolio() { return <><Header/><main><PageHero eyebrow="YOUR GOALS · PROTECT & GROW YOUR WEALTH" title="Design your portfolio" copy="Build an investment strategy designed around your objectives, preferences and desired level of involvement."/><PageIntro eyebrow="INVESTMENT STRATEGY" title="Coherence & clarity" copy="A team of in-house strategists will remain by your side to translate macro-economic and market events into actionable investment ideas."/><section className="split-section"><div className="statement-panel"><p className="eyebrow">PORTFOLIO BLUEPRINT</p><h2>Clear choices. Connected decisions.</h2><p>Our advisers connect your investment strategy to the rest of your financial life, revisiting the plan as your priorities evolve.</p></div><div className="allocation-art" aria-label="Illustration of a diversified portfolio"><span>STRATEGIC ASSET<br/>ALLOCATION</span><i/><i/><i/><i/></div></section><section className="principles"><article><span>01</span><h2>Research & Guidance</h2><p>Our team of strategists analyse and explain complex situations and concepts.</p></article><article><span>02</span><h2>Responsiveness</h2><p>Strategists react to market events with timely research and guidance.</p></article><article><span>03</span><h2>Actionable ideas</h2><p>Translate investment themes into opportunities relevant to your strategy.</p></article></section><ContactBand/></main><Footer/></> }

const coreMarkets = [['Equities', 'Participate in the long-term growth of companies, sectors and themes.'], ['Funds & ETFs', 'Access diversified strategies through a carefully assessed manager universe.'], ['Bonds', 'Balance income, duration and credit quality around your objectives.'], ['Structured Products', 'Define a specific market outcome with understood parameters and risks.'], ['Hedge Fund Strategies', 'Specialist strategies designed to complement traditional allocations.'], ['Funds', 'Access professionally managed investment strategies.']]
const diversifiers = [['Private Equity', 'Long-horizon access to businesses beyond public markets.'], ['Private Real Estate', 'Income and diversification through selected real-asset opportunities.'], ['Private Infrastructure', 'Exposure to essential assets supporting the modern economy.'], ['Private Credit', 'A flexible source of return and diversification in private markets.'], ['Tailored Hedge Fund Solutions', 'Specialist strategies designed around a distinct portfolio role.']]

function InvestmentUniverse() { return <><Header/><main><PageHero eyebrow="YOUR GOALS · PROTECT & GROW YOUR WEALTH" title="Benefit from a carefully selected investment universe" copy="Explore traditional, specialist and private-market opportunities within a coherent investment framework." tone="ink"/><PageIntro eyebrow="INVESTMENT UNIVERSE" title="Choice is valuable when it is intentional." copy="We evaluate opportunities through the lens of portfolio role, manager quality, liquidity and risk—so every allocation has a clear purpose in your plan."/><section className="universe-section"><div className="section-heading"><p className="eyebrow">TRADITIONAL & BESPOKE ASSET CLASSES</p><h2>Build from a strong foundation.</h2><p>Use established building blocks to pursue growth, income and resilience across global markets.</p></div><div className="universe-grid">{coreMarkets.map(([title, copy], index) => <article className="universe-card" key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p><a href="#contact">Find out more <b>→</b></a></article>)}</div></section><section className="diversifier-section"><div className="diversifier-copy"><p className="eyebrow">DIVERSIFICATION ASSETS</p><h2>Expand your opportunity set.</h2><p>When appropriate for your objectives and liquidity profile, specialist assets can add distinct sources of return and diversification.</p><a className="button button--dark" href="#contact">Discuss your investment objectives</a></div><div className="diversifier-list">{diversifiers.map(([title, copy]) => <article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></section><section className="disclosure"><p><strong>Important:</strong> All investments involve risk. Availability and suitability depend on your circumstances, investment objectives and jurisdiction. This page provides general information only and is not investment advice.</p></section><ContactBand/></main><Footer/></> }

function ServiceModel() { return <><Header/><main><PageHero eyebrow="YOUR GOALS · PROTECT & GROW YOUR WEALTH" title="Choose the level of service that suits you." copy="Select the degree of guidance, collaboration and day-to-day support that fits how you want to manage your wealth."/><PageIntro eyebrow="HOW WE WORK" title="One relationship. A wider circle of expertise." copy="Your lead adviser coordinates a multidisciplinary team across investment, lending, planning and family governance—bringing in the right specialists when a decision needs depth."/><section className="service-model"><div className="section-heading"><p className="eyebrow">THREE WAYS TO ENGAGE</p><h2>Your role, made clear.</h2></div><div className="service-grid"><article><span className="service-number">01</span><h3>Advisory partnership</h3><p>Make the final decisions with structured guidance, research and an adviser who challenges your thinking.</p><ul><li>Dedicated adviser</li><li>Portfolio recommendations</li><li>Regular strategy reviews</li></ul></article><article className="service-grid__featured"><span className="service-number">02</span><p className="card-kicker">SIGNATURE SERVICE</p><h3>Delegated stewardship</h3><p>Set the mandate and guardrails; our investment specialists handle implementation and ongoing adjustments.</p><ul><li>Defined investment mandate</li><li>Active monitoring</li><li>Transparent reporting</li></ul></article><article><span className="service-number">03</span><h3>Specialist access</h3><p>Engage our experts around a specific project, investment question or complex wealth-planning requirement.</p><ul><li>Focused expertise</li><li>Project-based support</li><li>Flexible engagement</li></ul></article></div></section><section className="relationship-section"><div><p className="eyebrow">THE RELATIONSHIP RHYTHM</p><h2>Always close to the decisions that matter.</h2></div><ol><li><span>01</span><div><h3>Listen</h3><p>Understand your context, ambitions and constraints.</p></div></li><li><span>02</span><div><h3>Align</h3><p>Agree the plan, responsibilities and decision cadence.</p></div></li><li><span>03</span><div><h3>Act & review</h3><p>Implement thoughtfully and keep the strategy connected to your life.</p></div></li></ol></section><ContactBand/></main><Footer/></> }

type PublicPageProps = { eyebrow: string; title: string; copy: string; intro: string; items: Array<[string, string]> }

function PublicPage({ eyebrow, title, copy, intro, items }: PublicPageProps) {
  return <><Header/><main><PageHero eyebrow={eyebrow} title={title} copy={copy}/><PageIntro eyebrow="OUR APPROACH" title={intro} copy="Our specialist teams combine structured advice with practical solutions designed around your circumstances and ambitions."/><section className="universe-section"><div className="section-heading"><p className="eyebrow">HOW WE CAN HELP</p><h2>Expertise for the decisions ahead.</h2></div><div className="universe-grid">{items.map(([heading, detail], index) => <article className="universe-card" key={heading}><span>0{index + 1}</span><h3>{heading}</h3><p>{detail}</p><a href="#contact">Find out more <b>→</b></a></article>)}</div></section><ContactBand/></main><Footer/></>
}

function PrepareForFuture() { return <PublicPage eyebrow="YOUR GOALS · PREPARE FOR YOUR FUTURE" title="Plan today for the life you want tomorrow." copy="Bring your personal, family and financial ambitions into one long-term plan." intro="A future-focused perspective on your wealth." items={[["Wealth planning", "Structure your assets around your family, ambitions and long-term priorities."], ["Family governance", "Create a shared framework for communication, decision-making and continuity."], ["Retirement planning", "Consider income, investment and protection needs across every stage of life."], ["Legacy planning", "Prepare the next generation with a thoughtful approach to wealth transfer."]]}/> }

function FinanceProjects() { return <PublicPage eyebrow="YOUR GOALS · FINANCE YOUR PROJECTS" title="Give your ambitions the financial backing they deserve." copy="Explore financing solutions that complement your wider wealth strategy." intro="Finance, considered alongside your whole financial picture." items={[["Real estate financing", "Structure property finance around your liquidity and long-term objectives."], ["Investment-backed lending", "Access liquidity while keeping your investment strategy in view."], ["Entrepreneurial finance", "Support business ambitions with coordinated advice and financing expertise."], ["Bespoke solutions", "Discuss complex financing requirements with the specialists best placed to help."]]}/> }

function AboutYou() { return <PublicPage eyebrow="ABOUT YOU" title="Expertise shaped around your world." copy="Our teams work with private clients, families and entrepreneurs facing distinct opportunities and responsibilities." intro="The right perspective starts with understanding you." items={[["Private clients", "Build, protect and pass on wealth with a relationship built around your priorities."], ["Entrepreneurs & families", "Coordinate business and personal wealth decisions across generations."], ["International clients", "Navigate cross-border considerations with global expertise and local insight."], ["Wealth management services", "Bring investments, financing and planning into one connected approach."]]}/> }

function Insights() { return <PublicPage eyebrow="INSIGHTS" title="Perspectives for a changing world." copy="Explore research, ideas and practical commentary from our investment and wealth specialists." intro="Stay connected to the themes shaping markets and wealth." items={[["Market outlook", "Consider the forces influencing global markets and the investment landscape."], ["Investment themes", "Explore long-term ideas designed to inform strategic conversations."], ["Wealth insights", "Read practical thinking on planning, family wealth and financial decision-making."], ["Expert voices", "Hear directly from specialists across investments, financing and wealth planning."]]}/> }

function Home() { return <><Header/><main><section className="home-hero"><div className="home-hero__grain" aria-hidden="true"/><div className="home-hero__content"><p className="eyebrow">BNP PARIBAS WEALTH MANAGEMENT</p><h1>Our 2026<br/><em>Investment Themes</em></h1><p className="home-hero__subtitle">Mid-Year Update</p><a className="button button--light" href={routes.universe}>Discover the themes <b>↗</b></a></div><div className="home-hero__index" aria-hidden="true"><span>01</span><i/><span>2026</span></div></section><section className="home-intro"><p className="eyebrow">LUXEMBOURG</p><h2>Expertise for your wealth, your projects and your future.</h2><p>Thanks to the international expertise of our teams and the know-how of the Luxembourg financial centre, we help address complex financial needs.</p><a className="text-link" href={routes.about}>Discover our approach <b>→</b></a></section><section className="home-services"><div className="home-services__intro"><p className="eyebrow">A CONNECTED VIEW</p><h2>Clarity for every part of your financial life.</h2></div><div className="home-services__list"><a href={routes.portfolio}><span>01</span><div><h3>Invest your wealth</h3><p>Build a strategy with purpose, perspective and structure.</p></div><b>↗</b></a><a href={routes.finance}><span>02</span><div><h3>Finance your projects</h3><p>Bring liquidity and long-term ambitions into balance.</p></div><b>↗</b></a><a href={routes.future}><span>03</span><div><h3>Prepare your future</h3><p>Create confidence for the generations and decisions ahead.</p></div><b>↗</b></a></div></section><ContactBand/></main><Footer/></> }

export default function App() { const path = window.location.pathname.replace(/\/$/, ''); if (path === routes.portfolio || path === '/wealth/design-your-portfolio') return <DesignPortfolio/>; if (path === routes.universe || path === '/wealth/investment-universe') return <InvestmentUniverse/>; if (path === routes.service || path === '/wealth/level-of-service') return <ServiceModel/>; if (path === routes.future) return <PrepareForFuture/>; if (path === routes.finance) return <FinanceProjects/>; if (path === routes.about) return <AboutYou/>; if (path === routes.insights) return <Insights/>; return <Home/> }
